### ISSUE TITLE
TypeError for column Container ID

### ISSUE THREAD

**Issue by VanessaKu** [amir9339/volatility-docker#26]
When running the  `--ps` or `--ps-extended` plugins on my dump with two running containers, I get the following error:

```
> python vol.py -f my_dump.raw linux.docker.Docker --ps-extended
Volatility 3 Framework 2.0.0
Progress:  100.00               Stacking attempts finished
Creation time (UTC)     Command Container ID    Is privileged   PID     Effective UID
Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\volatility3\vol.py", line 10, in <module>
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\cli\__init__.py", line 625, in main
    CommandLine().run()
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\cli\__init__.py", line 333, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\cli\text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\framework\renderers\__init__.py", line 215, in populate
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\framework\renderers\__init__.py", line 275, in _append
    return self._insert(parent, None, values)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\framework\renderers\__init__.py", line 290, in _insert
    tree_item = TreeNode(newpath, self, parent, values)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\framework\renderers\__init__.py", line 59, in __init__
    self._validate_values(values)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility3\framework\renderers\__init__.py", line 81, in _validate_    raise TypeError(
TypeError: Values item with index 2 is the wrong type for column Container ID (got <class 'NoneType'> but expected <class 'str'>)
```

I was able to "fix" it by changing `def get_container_id(self, container_pid)` to return an empty string instead of `None` if no container id is found. Is there a better solution?

**Comment by oshaked1** [comment]
Can you upload the memory dump that causes this error along with a profile for it? You can use https://www.file.io/ to upload it.
If this is an issue, please do as following:
1. Run linux.pslist.PsList --nsinfo and upload the output.
2. For each unique mount namespace (MNT_NS) in the pslist output, choose a single corresponding PID and run linux.mount.Mount --pid <PID>.
3. Upload all outputs from the mount plugin.

This will help to understand why a container ID could not be found.

**Comment by VanessaKu** [comment]
Sadly, I cannot upload the dump as it is too big (1GB).
It is a debian11 virtualbox dump with the following profile: https://file.io/KoIOsej4JnLf
It runs a docker-compose file I added here: https://gist.github.com/VanessaKu/4b5c80a1211aa2f286fbaf5645dc69a7

In that gist I also added the output of the commands you requested. 
But I did it only for the two docker container process mount namespaces, is that enough or do you really need _all_?

**Comment by oshaked1** [comment]
The output you provided is enough.
It seems that Debian 11 uses cgroups v2 which is not yet widely used, and it breaks the container id detection logic.
The temporary workaround you suggested was applied, but we will find a proper fix for this.

**Comment by oshaked1** [comment]
I added an additional container ID detection logic for cases where the cgroup method fails.
Please let us know if it works as expected for you.
Thank you for pointing this issue out!

**Comment by VanessaKu** [comment]
I can happily confirm that it works well, the container ids are now shown.
Thank you very much for your help and the really fast reaction!

```
Container ID    Command Creation Time (UTC)     PID

ec3ff5333a4     nginx   2022-01-29 21:44:15.247 2795
7d9b1159059     mysqld  2022-01-29 21:44:15.507 2803
```
